---
- name: Setup global facts directory.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/ansible
    - /etc/ansible/facts.d
    
- name: Add syncthing fact.
  template:
    src: syncthing.fact.j2
    dest: /etc/ansible/facts.d/syncthing.fact
    owner: root
    group: root
    mode: 0755
    
- name: Add syncthing key
  apt_key:
    url: https://syncthing.net/release-key.txt

- name: Add syncthing repo
  apt_repository: 
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install syncthing
  apt:
    name: syncthing
    state: present
    update_cache: yes

- name: Increase watches for syncthing.
  sysctl:
    name: fs.inotify.max_user_watches
    value: '204800'
    sysctl_set: yes
    state: present
    reload: yes

- name: Create systemd user directory
  file:
    path: "/home/{{ syncthing_user }}/.config/systemd/user/"
    state: directory
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"

- name: Move syncthing.service to user dir
  copy:
    src: /usr/lib/systemd/user/syncthing.service
    dest: "/home/{{ syncthing_user }}/.config/systemd/user/"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"

- name: Enable and start syncthing service as user 
  systemd:
    name: syncthing.service
    enabled: yes
    state: started
    scope: user
  become: yes
  become_user: "{{ syncthing_user }}"
